server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092  
    consumer:
      group-id: order-service-group

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: order-service  
    
  management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  